[package]
name = "rag"
version = "0.1.0"
edition = "2021"

[dependencies]
common.workspace = true
storage.workspace = true
document.workspace = true
rag-config.workspace = true
async-openai.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
tokio.workspace = true
