[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "index.html", "input.css"]

[serve]
address = "127.0.0.1"
port = 8081

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -i input.css -o output.css"]
